# Generated by Django 6.0.1 on 2026-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_url', models.URLField()),
                ('short_url', models.CharField()),
                ('num_use', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
