# Generated by Django 6.0 on 2026-01-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_url',
            new_name='short_suffix',
        ),
    ]
