# Generated by Django 6.0.1 on 2026-01-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_rename_short_url_shorturl_short_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='short_suffix',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
